[phases.setup]
nixPkgs = ["nodePackages.npm", "python3", "python3Packages.pip", "gcc", "gnumake", "openssl"]

[phases.install]
cmds = [
    "npm install",
    "python3 -m venv /app/venv",
    "/app/venv/bin/pip install --upgrade pip",
    "/app/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
    "npm run build",
    "/app/venv/bin/python3 -c 'import urllib3; print(\"VENV Verified\")'"
]

[start]
cmd = "node server.js"
