[phases.setup]
nixPkgs = [
  "nodejs",
  "python312",
  "python312Packages.pip",
  "gcc",
  "gnumake",
  "openssl"
]

[phases.install]
cmds = [
  "npm install",
  "python3 -m pip install --no-cache-dir -r backend/requirements.txt"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "node server.js"