
import { STRATEGIES_REPOSITORY as DYNAMIC_REPOSITORY } from '../services/strategyRegistry';
import { StrategyDefinition } from '../types';

// Exporting the dynamic repository generated by the Registry
export const STRATEGIES_REPOSITORY: StrategyDefinition[] = DYNAMIC_REPOSITORY;
